version: '3'
services:
  redis:
    image: redis
  web:
    # COMPLETE HERE
    build: .
    ports:
      - "10000:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
